"""Canonical sequence-level geometry contracts and providers for P3-0."""

from .depth_alignment import (
    DepthAlignmentModelSelection,
    GlobalDepthAlignmentMethod,
    PerFrameDepthAlignment,
    SequenceDepthAlignmentResult,
    apply_depth_alignment,
    apply_sequence_depth_alignment,
    align_depth_sequence_to_reference,
    estimate_depth_alignment,
    estimate_depth_alignment_from_correspondences,
    estimate_depth_alignment_with_holdout,
    select_depth_alignment_from_correspondences,
    select_depth_alignment_model,
)
from .motion_regime import (
    CameraMotionRegime,
    MotionRegimeObservation,
    MotionRegimeThresholds,
    classify_motion_regime,
)
from .observation import (
    DepthAlignmentMode,
    DepthAlignmentObservation,
    RelativePoseObservation,
    SequenceGeometryObservation,
    SequenceScaleStatus,
    Shared3DClipObservation,
)
from .provider import (
    BaseSceneCutDetector,
    BaseSequenceGeometryProvider,
    ForegroundMaskObservation,
    HistogramFeatureSceneCutDetector,
    LegacyDepthPoseSequenceAdapter,
    MockSequenceGeometryProvider,
    SceneCutDecision,
    SyntheticSequenceGeometryProvider,
    UnifiedSequenceGeometryProvider,
    build_foreground_mask,
)
from .pose_estimation import (
    BackgroundTrackDiagnostics,
    LayeredPoseEstimator,
    PoseEstimateCandidate,
    PoseModelType,
    PosePairEstimation,
    TranslationScaleStatus,
    estimate_adaptive_pose_candidates,
    estimate_essential_pose_from_correspondences,
    estimate_rotation_pose_from_correspondences,
    track_background_correspondences,
)
from .pose_graph import PoseGraphResult, build_pose_graph
from .quality import SequenceGeometryQuality
from .stabilization import (
    Dynamic3DFrameValidity,
    SequenceGeometryStabilizationResult,
    stabilize_sequence_geometry,
)

__all__ = [
    "BaseSceneCutDetector",
    "BaseSequenceGeometryProvider",
    "BackgroundTrackDiagnostics",
    "CameraMotionRegime",
    "DepthAlignmentMode",
    "DepthAlignmentModelSelection",
    "DepthAlignmentObservation",
    "Dynamic3DFrameValidity",
    "ForegroundMaskObservation",
    "GlobalDepthAlignmentMethod",
    "HistogramFeatureSceneCutDetector",
    "LayeredPoseEstimator",
    "LegacyDepthPoseSequenceAdapter",
    "MockSequenceGeometryProvider",
    "MotionRegimeObservation",
    "MotionRegimeThresholds",
    "PerFrameDepthAlignment",
    "PoseEstimateCandidate",
    "PoseGraphResult",
    "PoseModelType",
    "PosePairEstimation",
    "RelativePoseObservation",
    "SceneCutDecision",
    "SequenceDepthAlignmentResult",
    "SequenceGeometryObservation",
    "SequenceGeometryStabilizationResult",
    "SequenceGeometryQuality",
    "SequenceScaleStatus",
    "Shared3DClipObservation",
    "SyntheticSequenceGeometryProvider",
    "TranslationScaleStatus",
    "UnifiedSequenceGeometryProvider",
    "apply_depth_alignment",
    "apply_sequence_depth_alignment",
    "align_depth_sequence_to_reference",
    "build_foreground_mask",
    "build_pose_graph",
    "classify_motion_regime",
    "estimate_adaptive_pose_candidates",
    "estimate_essential_pose_from_correspondences",
    "estimate_rotation_pose_from_correspondences",
    "estimate_depth_alignment",
    "estimate_depth_alignment_from_correspondences",
    "estimate_depth_alignment_with_holdout",
    "select_depth_alignment_from_correspondences",
    "select_depth_alignment_model",
    "stabilize_sequence_geometry",
    "track_background_correspondences",
]
